version: "3.6"

services:
  surface:
    network_mode: host
    build: ./
    image: uwrov/pi_base:latest
    container_name: pi 
    environment:
      - ROS_HOSTNAME=${HOSTNAME}
      - ROS_IP=${IP}
      - PIGPIO_ADDR=${HOSTNAME}
      - ROS_MASTER_URI=${URI}
      - ROS_LOG_DIR=/root/logs
      - LD_LIBRARY_PATH=/opt/vc/lib
      - PYTHONPATH=/usr/local/lib/python3.8/site-packages
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - type: volume
        source: nautilus_logs
        target: /root/logs
      - type: bind
        source: ./src
        target: /root/catkin_ws/src
      - type: bind
        source: /opt/vc
        target: /opt/vc

volumes:
  nautilus_logs:
    external: true
